version: '3.5'
services:
  apache:
    container_name: "creiwork-v3-dev"
    build: https://github.com/creios/docker-creiwork.git#v3-dev
    links:
      - mysql
    dns:
      - 8.8.8.8
      - 9.9.9.9
    ports:
      - "80:80"
    volumes:
      - .:/var/www
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: creiwork
      MYSQL_USER: creiwork
      MYSQL_PASSWORD: creiwork