version: '3.5'
services:
  php:
    build: .
    networks:
      - webserver
      - database
      - mailcatcher
      - xhgui
    volumes:
      - ./docker/php:/usr/local/etc/php-docker
      - .:/var/www
      - ./docker/xdebug/profiling:/tmp/xdebug
      - type: bind
        read_only: true
        source: ./docker/xhgui/config/config.php
        target: /xhgui-service/config/config.php
      - type: bind
        read_only: true
        source: ./docker/xhgui/config/config.php
        target: /xhgui-service/config/config.default.php
      - type: volume
        read_only: true
        source: xhgui-source
        target: /xhgui-service
  nginx:
    image: nginx:1.15
    networks:
      - webserver
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./public:/var/www/public
      - ./static:/var/www/static
      - ./docker/nginx/config:/etc/nginx/conf.d
      - ./docker/nginx/certs:/etc/ssl
  mariadb:
    image: mariadb:10.3
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: creiwork
  adminer:
    image: adminer
    networks:
      - database
    ports:
      - 8081:8080
    environment:
      ADMINER_DEFAULT_SERVER: 'mariadb'
  mailcatcher:
    image: schickling/mailcatcher
    networks:
      - mailcatcher
    ports:
      - "1080:1080"
  webgrind:
    image: devgeniem/webgrind
    ports:
      - "8082:80"
    volumes:
      - ./docker/xdebug/profiling:/tmp/xdebug
    environment:
      XDEBUG_OUTPUT_DIR: "/tmp/xdebug"
  xhgui:
    image: edyan/xhgui:php7.2
    networks:
      - xhgui
    ports:
      - "8083:80"
    volumes:
      - type: bind
        read_only: true
        propagation: shared
        source: ./docker/xhgui/config/config.php
        target: /usr/local/src/xhgui/config/config.php
      - type: bind
        read_only: true
        propagation: shared
        source: ./docker/xhgui/config/config.php
        target: /usr/local/src/xhgui/config/config.default.php
      - type: volume
        read_only: false
        source: xhgui-source
        target: /usr/local/src/xhgui
networks:
  webserver:
  database:
  mailcatcher:
  xhgui:
volumes:
  xhgui-source: