version: '3.5'
services:
  apache:
    build: .
    links:
      - mysql
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: creiwork
