version: '3.5'
services:
  php:
    build: .
    networks:
      - webserver
      - database
      - mailcatcher
    volumes:
      - ./docker/php:/usr/local/etc/php-docker
      - .:/var/www
  nginx:
    image: nginx:1.15
    networks:
      - webserver
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./public:/var/www/public
      - ./static:/var/www/static
      - ./docker/nginx/config:/etc/nginx/conf.d
      - ./docker/nginx/certs:/etc/ssl
  mariadb:
    image: mariadb:10.3
    networks:
      - database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: creiwork
  mailcatcher:
    image: schickling/mailcatcher
    networks:
      - mailcatcher
    ports:
      - "1080:1080"
networks:
  webserver:
  database:
  mailcatcher:

