routes:
  - [GET, /,              Controller->index]
  - [GET, /json,          Controller->json]
  - [GET, /robo-file      Controller->roboFile]
  - [GET, /json/download, Controller->jsonDownload]
  - [GET, /redirect,      Controller->redirect]
  - [GET, /error,         Controller->error]

fallback: Error->notFound

baseNamespace: Creios\Creiwork\Controller
